### ISSUE TITLE
Minor improvements and cleaning

### ISSUE THREAD

**Issue by therealsujitk** [vatz88/FFCSonTheGo#193]
- [ ] Remove unused resources and redundant code (#208)
- [ ] Update / Remove deprecated code (#208)
- [ ] Move functions and rules into separate files (#208)
    - [ ] Move JS functions into separate files (Ex: `course-panel.js`, `timetable.js`, `course-list.js`)
    - [ ] Move SCSS rules into separate files (Ex: `course-panel.scss`, `timetable.scss`, `course-list.scss`)
- [ ] Normalise variable names, ids and classes (Keep a consistent naming scheme) (#208)
- [ ] Improve the slot filter algorithm (#198)
- [x] Improve screenshots (#189)
- [x] Add the last updated semester in [`package.json`](https://github.com/vatz88/FFCSonTheGo/blob/master/package.json) (#191)
- [ ] Update dependencies and devDependencies 
- [x] Add badges to [`README.md`](https://github.com/vatz88/FFCSonTheGo/blob/master/README.md) (#192)
- [ ] Update the [`README.md`](https://github.com/vatz88/FFCSonTheGo/blob/master/README.md) preview GIF
- [ ] Update [`CONTRIBUTING.md`](https://github.com/vatz88/FFCSonTheGo/blob/master/.github/CONTRIBUTING.md) (#195)

**Note:** Most editors like Visual Studio Code or IntelliJ show you what is deprecated with a ~~strikethrough~~.

**Comment by vatz88** [comment]
Updating CONTRIBUTING.md can be a separate issue and PR

**Comment by therealsujitk** [comment]
@vatz88 why are the packages `sass` and `xlsx` devDependencies? Shouldn't they by dependencies? I assume it's running properly on Netlify because it installs devDependencies as well.

Also, it doesn't look like `@sentry/browser` is being used. Can I remove it?

**Comment by therealsujitk** [comment]
@vatz88 when free, do you think you can add the [`hacktoberfest`](https://github.com/topics/hacktoberfest) topic to this repository so that PRs will count as valid contributions during this event. As of October 2021 they said only if a repository has this topic or if PRs have a `hacktoberfest` label they will be counted as contributions.

![image](https://user-images.githubusercontent.com/60378235/145673966-8423f7ef-8c95-484e-a20d-97d23464491b.png)

**Comment by vatz88** [comment]
@therealsujitk done

**Comment by therealsujitk** [comment]
I've added updating the node version as a task here. ~ https://github.com/vatz88/FFCSonTheGo/issues/231#issuecomment-1785983401
